#!/bin/bash

function runnable
{
	cmd=$1
	shift
	$BIN_DIR/collab_res/collab-$cmd $@
}

function helpall
{
	runnable init help
	runnable start help
	runnable destroy help
	runnable ssh help
	runnable auth help
}

if [ $# -lt 1 ]; then
	helpall
else
	if [[ "$1" == "init" ]]; then
		shift
		runnable init $@
	elif [[ "$1" == "start" ]]; then
		shift
		if [ $# -lt 1 ]; then
			runnable start help
		else
			runnable start $@
		fi
	elif [[ "$1" == "destroy" ]]; then
		runnable destroy
	elif [[ "$1" == "ssh" ]]; then
		shift
		runnable ssh $@
	elif [[ "$1" == "auth" ]]; then
		shift
		if [ $# -lt 2 ]; then
			runnable auth help
		else
			runnable auth $@
		fi
	else
		helpall
	fi
fi
